### ISSUE TITLE
Table description off to the left

### ISSUE THREAD

**Issue by littledan** [bterlson/ecmarkup#64]
E.g., http://tc39.github.io/ecmascript_simd/#simd-descriptor-table

SIMD type descriptors is aligned to the left, rather than the center.

**Comment by bterlson** [comment]
This seems fixed in the latest emu. Can you confirm?

**Comment by littledan** [comment]
I'm still seeing it off to the left.

![screenshot 2015-10-19 at 11 52 33 am](https://cloud.githubusercontent.com/assets/189835/10574740/46ac7a64-7658-11e5-80be-63d20addd1de.png)

**Comment by littledan** [comment]
Oh sorry was this a stylesheet change, or that I have to rebuild the file?

**Comment by bterlson** [comment]
Requires both a rebuild with latest and a new stylesheet.

**Comment by bterlson** [comment]
Feel free to reopen if this isn't fixed!
